#!/usr/bin/python3

import h5py
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Parsing HDF5')
    parser.add_argument('filename')
    args = parser.parse_args()
    print(args.filename)


