#!/usr/bin/python3

import h5py
import argparse
import sys

# TODO make this add all synchronous data to a global plot
def plot_datasets(name):
    print(name)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Parsing HDF5')
    parser.add_argument('filename')
    args = parser.parse_args()

    try:
        f = h5py.File(args.filename, 'r')
    except:
        print(f'Something went wrong opening \'{args.filename}\'')
    else:
        f.visit(plot_datasets)
